[test]
preload = ["./web/testing/happy-dom.ts", "./web/testing/svelte-loader.ts"]
coverageDir = "dist/coverage"
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["web/testing/**"]
