// Content fingerprint of the extraction code — the "code" half of the cache
// key (see src/cache.rs). Hashes every Rust source of THIS crate plus the
// embedded extract.nix and highlight queries, so any change to code that
// shapes blob contents invalidates cached blobs with no manual version bump.
//
// WHAT THIS TOKEN IS. Not a byte-reproducibility token — a SEMANTIC-VALIDITY
// one. It does not promise that the same fingerprint reproduces the same bytes,
// and it never could: extract_options derives its worker count from
// available_parallelism() (options.rs), and workers accumulate into
// shared.results in COMPLETION order, so the order of ConfigData.options — and
// with it the fileIndex key order and every defines/declares index built from
// it — varies run to run and differs between a 4-core and a 16-core machine.
// Measured, not deduced: ten identical runs against fixtures/mini-flake on a
// 10-core host produced five distinct option orderings and five distinct blob
// hashes. So identical fingerprint plus identical cache key ALREADY yields
// different bytes, legitimately. What the fingerprint claims is narrower and
// still worth having: that a cached blob's CONTENT MODEL — which options exist,
// what each field means, how values were scrubbed and shaped — is the one this
// build of the extractor would produce today.
//
// WHY THE BOUNDARY CAN BE NARROWED AT ALL. Because manifest.json is write-only.
// Nothing ever reads it back: it is regenerated by build_manifest on every
// `extract` run, every `serve` start and every POST /api/refresh, and the only
// disk reads in the program are blobs, sidecars, the UI bundle and source
// files. So manifest-only code CANNOT serve stale data — the worst it can do is
// produce a manifest that is immediately overwritten. The fingerprint's entire
// staleness-prevention job is gating exactly two artifacts, the ConfigData and
// PackageData blobs, through the `meta.extractor != FINGERPRINT` check in
// reconcile_one. That asymmetry, not a judgment about which code is "really"
// extraction, is what makes leaving serve.rs and export.rs outside safe.
//
// The boundary is the crate, not a curated list of files. A list was always
// the obvious way to stop orchestration-only edits — serve.rs, page.rs,
// export.rs — from throwing away every user's cached extractions, and it was
// always the wrong way: a forgotten entry serves stale data with no error
// message, while the whole-tree hash it would have replaced only ever cost one
// spurious re-extraction. Hashing a crate keeps the safe direction of that
// trade and deletes the failure mode instead of accepting it. There is no list
// to forget an entry from, and a module outside this crate cannot end up in a
// blob because it cannot be reached from inside one.
//
// The crate is deliberately a SUPERSET of the blob-affecting set, and that is
// not an oversight to tidy up later. git.rs, scan.rs and pathref.rs reach
// manifest.json only, so by the paragraph above they cannot cause staleness and
// a tighter boundary could exclude them. They stay in because the cost of being
// wrong is asymmetric — one spurious re-extraction against silently serving
// stale data — and because a crate you can describe in one sentence ("anything
// the extractor can serialise") survives contact with future edits better than
// one that needs a per-module staleness proof. Moving code OUT of here is the
// change that needs the careful argument, not moving code in.
//
// What the crate boundary does NOT cover: extraction PARAMETERS come from the
// binary crate and this hash cannot see them. Exactly one does — the timeout,
// threaded from main.rs's --timeout through drive.rs and serve.rs into
// extract_options. (concurrency and skip_invisible are ExtractOptionsOpts
// defaults, so they live in here. Which configurations get requested is not a
// blob-contents question: blobs are per-configuration, so an unrequested one
// stays pending rather than being written thin.) A timeout is an eval failure
// like any other, so too short a one walks options.rs's ladder — split, then
// values skipped, then descriptions skipped, then abandoned — and writes a
// genuinely thinner blob. Its sidecar records nothing about the timeout that
// produced it, so it is then fresh forever.
//
// That hazard is real, but it is not new and it is not something this hash was
// ever protecting. --timeout is a runtime input: the same binary at the same
// fingerprint already accepts a blob extracted under `--timeout 5` as fresh for
// a later `--timeout 600`. It is not even reliably user-driven — whether a chunk
// times out also turns on machine load, on whether nix's eval cache is warm and
// on network latency for uncached inputs, so the same command on the same host
// can write a full blob or a degraded one. Hashing source cannot close any of
// that; no property of the source is what varied. All the whole-tree
// hash covered was the narrower case of someone editing the default in the
// binary crate, and that is the entire cost of moving to a crate boundary.
// Two properties bound it: degradation only ever subtracts — the ladder drops
// values and descriptions, it cannot invent a wrong one — and it is loud, since
// every rung taken and every chunk abandoned pushes a warning into the sidecar
// that reconcile re-emits as "[cached] …" on every later run. A degraded blob
// keeps announcing itself for as long as it is cached, which is the opposite of
// the silent-stale-data failure the curated list would have risked.
//
// If the parameter hole is ever worth closing, the fix is to record the
// degradation-relevant parameters in the sidecar, so a blob extracted under a
// tighter timeout is stale by construction. That closes the CLI-flag case as
// well, which no amount of source hashing reaches.

use sha2::{Digest, Sha256};
use std::collections::{HashSet, VecDeque};
use std::path::{Path, PathBuf};

fn main() {
    // Cargo always sets CARGO_MANIFEST_DIR for build scripts; "." is an inert
    // stand-in that keeps this panic-free rather than a path anyone builds from.
    let root =
        std::env::var_os("CARGO_MANIFEST_DIR").map_or_else(|| PathBuf::from("."), PathBuf::from);

    let mut files: Vec<PathBuf> = Vec::new();
    // EVERY file under src/, whatever its extension — not the .rs files plus a
    // list of the others. extract.nix and the two vendored .scm queries used to
    // be named here one by one, which made the "there is no list to forget an
    // entry from" claim above false: a third grammar added tomorrow would have
    // silently escaped the fingerprint and served every user stale blobs. The
    // claim is now true by construction, which was the whole point.
    //
    // Two consequences, both chosen rather than tolerated. It over-hashes:
    // vendor/nix-highlights.scm is provably NOT blob-affecting, since
    // tokenize_nix reaches only export.rs and serve.rs and both are render
    // paths, so editing it costs one spurious re-extraction. And a stray file
    // under src/ — a .DS_Store, an editor backup — feeds the hash too, so a
    // local build can disagree with a build from the git tree. Both are the
    // over-invalidation direction, which is the affordable one; any exclusion
    // rule sharp enough to avoid them would be a list, and a forgotten list
    // entry is the silent-staleness failure this exists to prevent.
    let mut dirs: Vec<PathBuf> = Vec::new();
    collect(&root.join("src"), &mut files, &mut dirs);
    // These two are outside src/ and cargo fixes their names, so naming them is
    // not an open-ended list. build.rs so the hash covers how it is computed;
    // Cargo.toml because it declares which dependencies this crate takes and,
    // where it spells them out locally rather than deferring to the workspace,
    // at which features.
    files.push(root.join("build.rs"));
    files.push(root.join("Cargo.toml"));
    files.sort();
    files.dedup();

    // The DIRECTORIES have to be watched, not just the files in them, and this
    // is load-bearing rather than belt-and-braces: rerun-if-changed on a file
    // fires when that file's contents change, so a set of per-file entries can
    // never notice a file being ADDED. Recursing over src/ above would then be
    // decorative — the walk would pick a new grammar up, but nothing would ask
    // it to run. Measured while building this: with files alone, dropping a new
    // .scm into src/vendor left the fingerprint untouched. Cargo rescans a
    // directory entry for modifications, so these cover additions and removals.
    dirs.sort();
    dirs.dedup();
    for d in &dirs {
        println!("cargo:rerun-if-changed={}", d.display());
    }

    let mut hasher = Sha256::new();
    for f in &files {
        let rel = f.strip_prefix(&root).unwrap_or(f);
        hasher.update(rel.to_string_lossy().as_bytes());
        hasher.update([0]);
        hasher.update(std::fs::read(f).unwrap_or_default());
        hasher.update([0]);
        println!("cargo:rerun-if-changed={}", f.display());
    }
    hasher.update(dependency_surface(&root).as_bytes());
    let digest = hex::encode(hasher.finalize());
    println!(
        "cargo:rustc-env=FLAKE_EXPLORER_FINGERPRINT=rs-{}",
        digest.get(..14).unwrap_or(&digest)
    );
}

// ------------------------------------------------------- dependency surface
//
// The source files above are not the whole input to a blob's bytes: the
// dependencies this crate resolves against are too, and they were invisible to
// the fingerprint. `cargo update` alone could rewrite every blob. It is not a
// theoretical route — serde_json's `preserve_order` decides whether every
// Value::Object in an option value keeps Nix's key order or gets re-sorted, and
// the tree-sitter-bash grammar version sets the node boundaries, and therefore
// the token runs, baked into every DrvPhase in a package blob.
//
// Deliberately the extraction crate's own resolved CLOSURE, not the whole
// Cargo.lock. This repo runs dependabot against a workspace whose other member
// pulls axum, tower, notify, futures and tokio-stream — none of which the
// extractor links. Hashing the whole lock would let an axum bump throw away
// every cached extraction for every user, which is the same over-invalidation
// the crate split exists to remove, just re-entered one level up.
//
// Derived by walking Cargo.lock rather than by shelling out to `cargo
// metadata`. Metadata was the obvious candidate and it does work here — checked,
// not assumed: a probe build script ran `cargo metadata --offline` successfully
// inside the crane sandbox. It was still the wrong tool. Its per-package feature
// lists are the precision we would want, but they come platform-filtered or not
// at all, and a fingerprint that varies by host would have two machines
// invalidating each other's blobs forever; a nested cargo invoked from a build
// script can also deadlock on the package-cache lock, which turns a wrong answer
// into a hung build. Cargo.lock is already the platform-independent resolved
// graph, needs no subprocess and no JSON parser.
//
// The gap that leaves is features: the lock records versions, not feature
// selections. Two things cover most of it. Feature changes usually move an
// optional dependency and so do show up in the lock — `preserve_order` above is
// exactly that case, since it is what pulls indexmap into serde_json. And the
// two manifests that can declare a feature are hashed: this crate's Cargo.toml
// in full, and from the workspace root only the [workspace.dependencies] entries
// naming a package in the closure, so an axum or tower entry still cannot reach
// the hash. A feature that neither moves a dependency nor appears in either
// place is the remaining hole, and it is narrower than what was open before.
//
// Every fallback below is toward over-invalidation. An unparseable lock hashes
// whole, an unparseable workspace-dependency block hashes whole. Being coarse
// costs a re-extraction; being silently narrow serves stale data.

/// The hashed representation of what this crate resolves against: one
/// `name version checksum` line per external package in its dependency
/// closure, sorted, plus the workspace dependency entries that named them.
fn dependency_surface(crate_dir: &Path) -> String {
    let Some(ws) = crate_dir
        .ancestors()
        .find(|d| d.join("Cargo.lock").is_file())
    else {
        // Cargo will not build without a lock, so this is unreachable in
        // practice; say so rather than silently contributing nothing.
        println!(
            "cargo:warning=no Cargo.lock found — dependency versions are NOT in the extraction fingerprint"
        );
        return String::new();
    };
    let lock_path = ws.join("Cargo.lock");
    let ws_manifest = ws.join("Cargo.toml");
    println!("cargo:rerun-if-changed={}", lock_path.display());
    println!("cargo:rerun-if-changed={}", ws_manifest.display());

    let lock = std::fs::read_to_string(&lock_path).unwrap_or_default();
    let me = std::env::var("CARGO_PKG_NAME").unwrap_or_default();

    let Some((closure, names)) = lock_closure(&lock, &me) else {
        println!(
            "cargo:warning=could not resolve {me}'s dependency closure from Cargo.lock — hashing the whole lock instead (over-invalidates, never under)"
        );
        return lock;
    };

    let mut out = closure.join("\n");
    if let Ok(manifest) = std::fs::read_to_string(&ws_manifest) {
        out.push('\n');
        out.push_str(&workspace_dep_entries(&manifest, &names));
    }
    out
}

#[derive(Default)]
struct LockPkg {
    name: String,
    version: String,
    /// Absent for workspace members and path dependencies — that absence is
    /// how they are told apart from registry packages.
    source: Option<String>,
    checksum: Option<String>,
    deps: Vec<String>,
}

/// `name version checksum` lines for every registry package reachable from
/// `root_name`, plus the set of package names in the closure. None when the
/// lock did not parse into something usable, which the caller turns into
/// hashing the whole file.
fn lock_closure(lock: &str, root_name: &str) -> Option<(Vec<String>, HashSet<String>)> {
    let pkgs = parse_lock(lock);
    let start = pkgs.iter().position(|p| p.name == root_name)?;

    let mut seen: HashSet<usize> = HashSet::from([start]);
    let mut queue: VecDeque<usize> = VecDeque::from([start]);
    let mut lines: Vec<String> = Vec::new();
    let mut names: HashSet<String> = HashSet::new();

    while let Some(i) = queue.pop_front() {
        let Some(pkg) = pkgs.get(i) else { continue };
        // A dependency reads as "name" or, when the lock carries more than one
        // version of it, "name version".
        for dep in &pkg.deps {
            let (dname, dver) = match dep.split_once(' ') {
                Some((n, v)) => (n, Some(v)),
                None => (dep.as_str(), None),
            };
            let Some(j) = pkgs
                .iter()
                .position(|p| p.name == dname && dver.is_none_or(|v| p.version == v))
            else {
                continue;
            };
            if seen.insert(j) {
                queue.push_back(j);
            }
        }
    }

    for p in seen.into_iter().filter_map(|i| pkgs.get(i)) {
        names.insert(p.name.replace('_', "-"));
        // Workspace members carry no source; their contents are hashed as
        // files, and folding their version in here would invalidate every
        // cached blob on a release bump that changed no extraction code.
        if p.source.is_none() {
            continue;
        }
        lines.push(format!(
            "{} {} {}",
            p.name,
            p.version,
            p.checksum.as_deref().unwrap_or("-")
        ));
    }
    if lines.is_empty() {
        return None;
    }
    lines.sort();
    Some((lines, names))
}

fn parse_lock(lock: &str) -> Vec<LockPkg> {
    let mut pkgs: Vec<LockPkg> = Vec::new();
    let mut cur: Option<LockPkg> = None;
    let mut in_deps = false;
    for line in lock.lines() {
        let t = line.trim();
        if t == "[[package]]" {
            pkgs.extend(cur.take());
            cur = Some(LockPkg::default());
            in_deps = false;
            continue;
        }
        if !in_deps && t.starts_with('[') {
            // [metadata], [[patch.unused]] and friends end the current package.
            pkgs.extend(cur.take());
            continue;
        }
        let Some(p) = cur.as_mut() else { continue };
        if in_deps {
            if t.starts_with(']') {
                in_deps = false;
            } else if let Some(d) = unquote(t.trim_end_matches(',')) {
                p.deps.push(d);
            }
            continue;
        }
        if t == "dependencies = [" {
            in_deps = true;
        } else if let Some(v) = kv(t, "name") {
            p.name = v;
        } else if let Some(v) = kv(t, "version") {
            p.version = v;
        } else if let Some(v) = kv(t, "source") {
            p.source = Some(v);
        } else if let Some(v) = kv(t, "checksum") {
            p.checksum = Some(v);
        }
    }
    pkgs.extend(cur.take());
    pkgs
}

/// The [workspace.dependencies] lines whose key names a package in the
/// closure. Version requirements and feature lists for this crate's deps live
/// there, since it declares most of them as `foo.workspace = true`.
fn workspace_dep_entries(manifest: &str, names: &HashSet<String>) -> String {
    let mut block: Vec<&str> = Vec::new();
    let mut inside = false;
    for line in manifest.lines() {
        let t = line.trim();
        if t.starts_with('[') {
            inside = t == "[workspace.dependencies]";
            continue;
        }
        if inside {
            block.push(line);
        }
    }

    let mut kept: Vec<&str> = Vec::new();
    for line in &block {
        let t = line.trim();
        if t.is_empty() || t.starts_with('#') {
            continue;
        }
        // Every entry here is one self-contained `key = value` line today. A
        // reformat into a multi-line inline table would make the key-matching
        // below skip the continuation lines and quietly narrow the hash, so
        // detect that shape and hash the whole block instead.
        if t.matches('{').count() != t.matches('}').count()
            || t.matches('[').count() != t.matches(']').count()
        {
            return block.join("\n");
        }
        let Some((key, _)) = t.split_once('=') else {
            return block.join("\n");
        };
        if names.contains(key.trim().replace('_', "-").as_str()) {
            kept.push(t);
        }
    }
    kept.sort_unstable();
    kept.join("\n")
}

fn kv(line: &str, key: &str) -> Option<String> {
    unquote(line.strip_prefix(key)?.trim_start().strip_prefix('=')?)
}

fn unquote(s: &str) -> Option<String> {
    Some(s.trim().strip_prefix('"')?.strip_suffix('"')?.to_string())
}

fn collect(dir: &Path, files: &mut Vec<PathBuf>, dirs: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    dirs.push(dir.to_path_buf());
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            collect(&p, files, dirs);
        } else {
            files.push(p);
        }
    }
}
