// Content fingerprint of the extraction code — the "code" half of the cache
// key (see src/cache.rs). Hashes every Rust source of THIS crate plus the
// embedded extract.nix and highlight queries, so any change to code that
// shapes blob contents invalidates cached blobs with no manual version bump.
//
// WHAT THIS TOKEN IS. Not a byte-reproducibility token — a SEMANTIC-VALIDITY
// one. It does not promise that the same fingerprint reproduces the same bytes,
// and it never could: extract_options derives its worker count from
// available_parallelism() (options.rs), and workers accumulate into
// shared.results in COMPLETION order, so the order of ConfigData.options — and
// with it the fileIndex key order and every defines/declares index built from
// it — varies run to run and differs between a 4-core and a 16-core machine.
// Measured, not deduced: ten identical runs against fixtures/mini-flake on a
// 10-core host produced five distinct option orderings and five distinct blob
// hashes. So identical fingerprint plus identical cache key ALREADY yields
// different bytes, legitimately. What the fingerprint claims is narrower and
// still worth having: that a cached blob's CONTENT MODEL — which options exist,
// what each field means, how values were scrubbed and shaped — is the one this
// build of the extractor would produce today.
//
// WHY THE BOUNDARY CAN BE NARROWED AT ALL. Because manifest.json is write-only.
// Nothing ever reads it back: it is regenerated by build_manifest on every
// `extract` run, every `serve` start and every POST /api/refresh, and the only
// disk reads in the program are blobs, sidecars, the UI bundle and source
// files. So manifest-only code CANNOT serve stale data — the worst it can do is
// produce a manifest that is immediately overwritten. The fingerprint's entire
// staleness-prevention job is gating exactly two artifacts, the ConfigData and
// PackageData blobs, through the `meta.extractor != FINGERPRINT` check in
// reconcile_one. That asymmetry, not a judgment about which code is "really"
// extraction, is what makes leaving serve.rs and export.rs outside safe.
//
// The boundary is the crate, not a curated list of files. A list was always
// the obvious way to stop orchestration-only edits — serve.rs, page.rs,
// export.rs — from throwing away every user's cached extractions, and it was
// always the wrong way: a forgotten entry serves stale data with no error
// message, while the whole-tree hash it would have replaced only ever cost one
// spurious re-extraction. Hashing a crate keeps the safe direction of that
// trade and deletes the failure mode instead of accepting it. There is no list
// to forget an entry from, and a module outside this crate cannot end up in a
// blob because it cannot be reached from inside one.
//
// The crate is deliberately a SUPERSET of the blob-affecting set, and that is
// not an oversight to tidy up later. git.rs, scan.rs and pathref.rs reach
// manifest.json only, so by the paragraph above they cannot cause staleness and
// a tighter boundary could exclude them. They stay in because the cost of being
// wrong is asymmetric — one spurious re-extraction against silently serving
// stale data — and because a crate you can describe in one sentence ("anything
// the extractor can serialise") survives contact with future edits better than
// one that needs a per-module staleness proof. Moving code OUT of here is the
// change that needs the careful argument, not moving code in.
//
// What the crate boundary does NOT cover: extraction PARAMETERS come from the
// binary crate and this hash cannot see them. Exactly one does — the timeout,
// threaded from main.rs's --timeout through drive.rs and serve.rs into
// extract_options. (concurrency and skip_invisible are ExtractOptionsOpts
// defaults, so they live in here. Which configurations get requested is not a
// blob-contents question: blobs are per-configuration, so an unrequested one
// stays pending rather than being written thin.) A timeout is an eval failure
// like any other, so too short a one walks options.rs's ladder — split, then
// values skipped, then descriptions skipped, then abandoned — and writes a
// genuinely thinner blob. Its sidecar records nothing about the timeout that
// produced it, so it is then fresh forever.
//
// That hazard is real, but it is not new and it is not something this hash was
// ever protecting. --timeout is a runtime input: the same binary at the same
// fingerprint already accepts a blob extracted under `--timeout 5` as fresh for
// a later `--timeout 600`. It is not even reliably user-driven — whether a chunk
// times out also turns on machine load, on whether nix's eval cache is warm and
// on network latency for uncached inputs, so the same command on the same host
// can write a full blob or a degraded one. Hashing source cannot close any of
// that; no property of the source is what varied. All the whole-tree
// hash covered was the narrower case of someone editing the default in the
// binary crate, and that is the entire cost of moving to a crate boundary.
// Two properties bound it: degradation only ever subtracts — the ladder drops
// values and descriptions, it cannot invent a wrong one — and it is loud, since
// every rung taken and every chunk abandoned pushes a warning into the sidecar
// that reconcile re-emits as "[cached] …" on every later run. A degraded blob
// keeps announcing itself for as long as it is cached, which is the opposite of
// the silent-stale-data failure the curated list would have risked.
//
// If the parameter hole is ever worth closing, the fix is to record the
// degradation-relevant parameters in the sidecar, so a blob extracted under a
// tighter timeout is stale by construction. That closes the CLI-flag case as
// well, which no amount of source hashing reaches.

use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

fn main() {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());

    let mut files: Vec<PathBuf> = Vec::new();
    collect(&root.join("src"), &mut files);
    files.push(root.join("build.rs"));
    files.push(root.join("src/extract.nix"));
    files.push(root.join("src/vendor/nix-highlights.scm"));
    files.push(root.join("src/vendor/bash-highlights.scm"));
    files.sort();
    files.dedup();

    let mut hasher = Sha256::new();
    for f in &files {
        let rel = f.strip_prefix(&root).unwrap_or(f);
        hasher.update(rel.to_string_lossy().as_bytes());
        hasher.update([0]);
        hasher.update(std::fs::read(f).unwrap_or_default());
        hasher.update([0]);
        println!("cargo:rerun-if-changed={}", f.display());
    }
    let digest = hex::encode(hasher.finalize());
    println!(
        "cargo:rustc-env=FLAKE_EXPLORER_FINGERPRINT=rs-{}",
        &digest[..14]
    );
}

fn collect(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            collect(&p, out);
        } else if p.extension().is_some_and(|x| x == "rs") {
            out.push(p);
        }
    }
}
